/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-variant": "var(--color-surface-variant)",
        "on-background": "var(--color-on-surface)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        primary: "var(--color-primary)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "primary-container": "var(--color-primary-container)",
        tertiary: "var(--color-tertiary)",
        "tertiary-dim": "var(--color-tertiary-dim)",
        secondary: "var(--color-secondary)",
        accent: "var(--color-accent)",
        cta: "var(--color-accent)",
        error: "var(--color-error)",
        "terminal-bg": "var(--color-terminal-bg)",
        ivory: "var(--color-on-surface)",
        mint: "var(--color-tertiary)",
        terracotta: "var(--color-accent)",
        "grey-green": "var(--color-on-surface-variant)",
        gothic: "var(--color-gothic)",
      },
      fontFamily: {
        display: ['"Playfair Display"', "serif"],
        serif: ['"Playfair Display"', "serif"],
        sans: ['"DM Sans"', "sans-serif"],
        mono: ['"JetBrains Mono"', "monospace"],
        "nav-link": ['"DM Sans"', "sans-serif"],
        "body-main": ['"DM Sans"', "sans-serif"],
        "code-block": ['"JetBrains Mono"', "monospace"],
        "label-caps": ['"DM Sans"', "sans-serif"],
        "terminal-sm": ['"JetBrains Mono"', "monospace"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-main": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-block": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "terminal-sm": ["13px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "nav-link": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "max-width": "1200px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      maxWidth: {
        "max-width": "1200px",
      },
      keyframes: {
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        blink: "blink 1s step-end infinite",
        fadeInUp: "fadeInUp 0.8s ease-out forwards",
      },
    },
  },
  plugins: [],
};
