/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0d1f1a",
        surface: "#0d1f1a",
        "surface-dim": "#051612",
        "surface-container-lowest": "#02110d",
        "surface-container-low": "#0d1f1a",
        "surface-container": "#11231e",
        "surface-container-high": "#1c2d28",
        "surface-container-highest": "#1d3d30",
        "surface-bright": "#2b3d37",
        "surface-variant": "#263833",
        "on-background": "#e8dcc8",
        "on-surface": "#e8dcc8",
        "on-surface-variant": "#6b7a74",
        outline: "#1d3d30",
        "outline-variant": "#3e4944",
        primary: "#e8dcc8",
        "primary-fixed": "#78d8b4",
        "primary-fixed-dim": "#6ecaa5",
        "primary-container": "#0d1f1a",
        tertiary: "#9effd9",
        "tertiary-dim": "#6ecaa5",
        secondary: "#b3ccc0",
        accent: "#a65d4a",
        cta: "#a65d4a",
        error: "#ffb4ab",
        "terminal-bg": "#0a1510",
        ivory: "#e8dcc8",
        mint: "#9effd9",
        terracotta: "#a65d4a",
        "grey-green": "#6b7a74",
        gothic: "#1d3d30",
      },
      fontFamily: {
        display: ['"Playfair Display"', "serif"],
        serif: ['"Playfair Display"', "serif"],
        sans: ['"DM Sans"', "sans-serif"],
        mono: ['"JetBrains Mono"', "monospace"],
        "nav-link": ['"DM Sans"', "sans-serif"],
        "body-main": ['"DM Sans"', "sans-serif"],
        "code-block": ['"JetBrains Mono"', "monospace"],
        "label-caps": ['"DM Sans"', "sans-serif"],
        "terminal-sm": ['"JetBrains Mono"', "monospace"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-main": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-block": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "terminal-sm": ["13px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "nav-link": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "max-width": "1200px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      maxWidth: {
        "max-width": "1200px",
      },
      keyframes: {
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        blink: "blink 1s step-end infinite",
        fadeInUp: "fadeInUp 0.8s ease-out forwards",
      },
    },
  },
  plugins: [],
};
